version: '3'
services:
  api:
    container_name:
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    ports:
      - '8080:8080'
  postgres:
    container_name:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - './postgresdata:/var/lib/postgresql/data'
      - './database.sql:/docker-entrypoint-initdb.d/dbinit.sql'
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD:
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '15432:80'
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    depends_on:
      - postgres

volumes:
  db-data: null
  pgadmin-data: null
